### ISSUE TITLE
{>>" # Hello.h \ Starlink team \ Big thank you the Help package 📦 Ukraine 🇺🇦🇺🇸

### ISSUE THREAD

**Issue by Johnjkovacs1994** [Starlink/dvi2bitmap#1]
{>>" # Thank you STARLINK TEAM the internet connection important. 🇺🇦🇺🇸 The internet communication always need the ARMY and the Normal-people too

**Comment by timj** [comment]
This is not the Starlink you are looking for. This is the Starlink that existed before Elon Musk reused the name.
